/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rura6502

fun main(args: Array<String>) {

  // 객체 선언
  class Test1

  // 객체 생성
  val test1_1: Test1 = Test1()
  // 타입 추론
  val test1_2 = Test1()

  class Test2 {
    // properties
    val key1 = "value1"  // 변경 가능
    var key2 = "value2"  // 변경 불가능
  }
  val test2_1  = Test2()
  println("test2_1's a is ${test2_1.key1}")
  test2_1.key2 = "value3"
  println("test2_1's a is ${test2_1.key2}")

  println()

  class Test3_1(key_value: String) { // 생성자
    val key = key_value;
  }
  class Test3_2(val key: String) // 위랑 같음
  val test3_1 = Test3_1("value1")
  val test3_2 = Test3_2("value2")
  println("test3_1 is ${test3_1.key}")
  println("test3_2 is ${test3_2.key}")

  println()

  class Test4(val key: String) {
    fun go(): String {
      return "key is $key"
    }
  }
  val test4 = Test4("KOTLIN")
  println(test4.go())
}

