  /*
  * This Kotlin source file was generated by the Gradle 'init' task.
  */
package io.github.rura6502

class App {
  val greeting: String
    get() {
      return "Hello world."
    }
}

fun main(args: Array<String>) {
  println(App().greeting)

  val a = 12;
  println("a is " + a);
  println("a is $a");
  println("a-1 is ${a-1}");

  println(/* you can write comment in middle of code */"Hello, World")

  if (1<2) {
    println("1<2 is true")
  } else {
    println("1<2 is false")
  }

  // kotlin if/when is expression. It menas those have return value
  val result = if (1<2) {
    "this is in true"
  } else {
    "this is in false"
  }
  println("result is -- $result")

  var x: Int = 10
  when (x) {
    0 -> println("x is 0")
    1,2 -> println("x is 1 or 2")
    in 3..5 -> println("x is in 3~5")
    else -> println("x is another")
  }

  for (i in 1..10) {
    println("i = $i in for")
  }

  var i = 1
  while (i <= 10) {
    println("i = $i in while")
    i++
  }
  do {
    i--
    println("i = $i in do")
  } while (i > 0)
}
