/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.rura6502;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.Random;

public class App {

  static final double W = 0.3;

  static PastData<Double> pastData = new PastData<>();
  static List<Double> EWMAs = new ArrayList<>();

  public static void main(String[] args) {
    for (int i=0; i<10; i++) {
      pastData.add((double) new Random().nextInt(10));
    }
    App.getEWMA(pastData);
    System.out.println(pastData);
    System.out.println(EWMAs);
  }

  public static void getEWMA(PastData<Double> pastData) {
    for (int i=0; i<pastData.size(); i++) {
      if (i == 0) {
        EWMAs.add(pastData.get(0));
      } else {
        double ewma = (W * pastData.get(i)) + ((1 - W)*EWMAs.get(i - 1));
        EWMAs.add(((int) (ewma * 100)) / 100d);
      }
        
    }
  }
  //   if 
  //   double sum = 0;
  //   for (int i=pastData.size(); i!=0; i--) {
  //     // sum += Math.pow((1-W)*W*pastData.get(i-1), i);
  //     sum += Math.pow((1-W), pastData.size() - i) * W * pastData.get(i-1);
  //   }
  //   EWMAs.add(   ((int) (sum * 100)) / 100d);
  //   return sum;
  // }
}


class PastData<T> extends ArrayList<T> {

  private static final long serialVersionUID = 1L;
  List<T> pastData = new ArrayList<>();

  public T poll() {
    T result = pastData.get(0);
    pastData.remove(0);
    return result;
  }
}
