/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.rura6502;

public class App {
  public static void main(String[] args) throws Exception {

    new UdpServer(9999).run();
  }
}
