/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rura6502

fun main(args: Array<String>) {
  

  // open은 이 클래스를 다른 클래스가 상속받을 수 있다는 의미
  // open 키워드 없이는 이 클래스를 다른 클래스가 상속받을 수 없음
  open class Person(val name: String) {
    fun say(): String {
      return "My name is $name, I am from ${country()}"
    }
    open fun country(): String { // 상속 받을 수 있는 method
      return "대한민국"
    }
  }
  class Student(name: String): Person(name) {
    override fun country(): String { // method 재정의, override
      return "미국"
    }
  }
  class Teacher(name: String): Person(name) {
    override fun country(): String {
      return "영국"
    }
  }

  val student1 = Student("student1")
  val teacher1 = Teacher("teacher1")
  println(student1.say())
  println(teacher1.say())
}
